### PR TITLE
#161054601 Build out the home page

### PR DESCRIPTION
**Pull request by kmwangemi**
**What does this PR do?**
Creates the home page for the web app.

**Description of Task to be completed?**
Lets the user navigate to the home page and provides links to login or register to the app

**How should this be manually tested?**
git clone https://github.com/kmwangemi/Store-Manager-App to your desired location on your machine.
Open the repository and go to index.html file
Launch the index.html file using your favorite web browser.

**What are the relevant pivotal tracker stories?
#161054601**

**Screenshot**

index

### CODE REVIEW

**Comment by SelaDanti** [comment]
Your UI is awesome, but in my opinion I would advice from using colours that fight i.e black and grey

**Comment by johnwayodi** [comment]
Great UI, I see a **Register** option, is it really required? As the Admin is the one who will be adding the sales attendants.

**Comment by Teatoller** [comment]
Hi, Kmwangemi,
Is this all or still in the works?

Regards
Steven Ennis

**Comment by kmwangemi** [comment]
@Waracci, @SelaDanti, @johnwayodi and @Teatoller  thanks so much for your observations. Surely Im going to implement the changes as soon as possible and am still working on the project @Teatoller .

**Comment by Paulstar200** [comment]
Good work. However change the colors. We can't have black on grey or vice versa. And we probably don't need the register as the admin will be adding the store attendants to the app.

**Pull request merged**
